/**
 * Analytics Event Tracking
 * Simple event tracking for birth chart features
 * Can be extended to integrate with Posthog, Google Analytics, etc.
 */

type EventName =
  | "chart_generated"
  | "chart_saved"
  | "chart_downloaded_png"
  | "chart_downloaded_pdf"
  | "chart_shared"
  | "chart_deleted"
  | "chart_viewed";

interface EventProperties {
  [key: string]: string | number | boolean | undefined;
}

/**
 * Extend Window interface to include analytics libraries
 */
interface WindowWithAnalytics extends Window {
  gtag?: (...args: unknown[]) => void;
  posthog?: {
    capture: (eventName: string, properties?: EventProperties) => void;
  };
}

/**
 * Track an analytics event
 * @param eventName - Name of the event
 * @param properties - Optional event properties
 */
export function trackEvent(eventName: EventName, properties?: EventProperties) {
  try {
    // Console log in development
    if (process.env.NODE_ENV === "development") {
      console.error(`[Analytics] ${eventName}`, properties);
    }

    // Send to Posthog if available
    if (typeof window !== "undefined" && (window as WindowWithAnalytics).posthog) {
      (window as WindowWithAnalytics).posthog?.capture(eventName, properties);
    }

    // Send to Google Analytics if available
    if (typeof window !== "undefined" && (window as WindowWithAnalytics).gtag) {
      (window as WindowWithAnalytics).gtag?.("event", eventName, properties);
    }

    // Custom analytics endpoint (optional)
    if (process.env.NEXT_PUBLIC_ANALYTICS_ENDPOINT) {
      fetch(process.env.NEXT_PUBLIC_ANALYTICS_ENDPOINT, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          event: eventName,
          properties,
          timestamp: new Date().toISOString(),
          url: typeof window !== "undefined" ? window.location.href : undefined,
        }),
      }).catch((error) => {
        console.error("[Analytics] Failed to send event:", error);
      });
    }
  } catch (error: unknown) {
    console.error("[Analytics] Error tracking event:", error);
  }
}

/**
 * Track chart generation
 */
export function trackChartGenerated(properties?: {
  hasChartName?: boolean;
  location?: string;
  timeZone?: string;
}) {
  trackEvent("chart_generated", properties);
}

/**
 * Track chart save
 */
export function trackChartSaved(properties?: { chartName?: string; autoGenerated?: boolean }) {
  trackEvent("chart_saved", properties);
}

/**
 * Track chart download (PNG)
 */
export function trackChartDownloadedPNG(properties?: { chartType?: string }) {
  trackEvent("chart_downloaded_png", properties);
}

/**
 * Track chart download (PDF)
 */
export function trackChartDownloadedPDF(properties?: { chartType?: string }) {
  trackEvent("chart_downloaded_pdf", properties);
}

/**
 * Track chart share
 */
export function trackChartShared(properties?: { method?: "link" | "social" }) {
  trackEvent("chart_shared", properties);
}

/**
 * Track chart delete
 */
export function trackChartDeleted(properties?: { chartId?: string }) {
  trackEvent("chart_deleted", properties);
}

/**
 * Track chart view
 */
export function trackChartViewed(properties?: {
  chartId?: string;
  source?: "my-kundlis" | "direct";
}) {
  trackEvent("chart_viewed", properties);
}
