/**
 * Phase-1 PDF Export Service
 * Client-side PDF generation using html2canvas + jsPDF
 * Desktop browser focus, low-risk implementation
 *
 * Based on: PDF Export Compatibility Analysis
 * Deferred: Mobile optimization, server-side, custom fonts (Phase-2+)
 */

import html2canvas from "html2canvas";
import { jsPDF } from "jspdf";
import type { ChartExportOptions, ReportExportOptions } from "./types";
import { PDF_LIMITS } from "./types";

/** Desktop-optimized scale (analysis §4.2, §7.1) - balance quality vs performance */
const DESKTOP_SCALE = 2;

/** Check if running in browser (SSR safety) */
function isBrowser(): boolean {
  return typeof window !== "undefined" && typeof document !== "undefined";
}

/** Detect mobile for quality scaling (analysis §4.3) */
function isMobileDevice(): boolean {
  if (!isBrowser()) return false;
  return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(
    navigator.userAgent
  );
}

/**
 * Memory-aware scale (analysis §4.3, §7.4):
 * - Desktop: scale 2
 * - iOS Safari: scale 1 (strict memory constraints)
 * - Other mobile: scale 2 if deviceMemory >= 4GB, else 1
 */
function getExportScale(): number {
  if (!isBrowser()) return DESKTOP_SCALE;
  if (!isMobileDevice()) return DESKTOP_SCALE;
  if (/iPhone|iPad|iPod/.test(navigator.userAgent)) return 1; // iOS: prefer stability
  const memory = (navigator as Navigator & { deviceMemory?: number }).deviceMemory;
  if (memory == null) return 1; // Unknown: prefer stability
  return memory >= 4 ? DESKTOP_SCALE : 1;
}

/**
 * Export a single chart element as PDF (Phase-1 primary path)
 * Captures DOM element via html2canvas, embeds in A4 PDF
 */
export async function exportChartAsPdf(
  options: ChartExportOptions
): Promise<void> {
  if (!isBrowser()) {
    throw new Error("PDF export requires browser environment");
  }

  const element = document.getElementById(options.elementId);
  if (!element) {
    throw new Error(`Element with ID "${options.elementId}" not found`);
  }

  const scale = getExportScale();

  const canvas = await html2canvas(element, {
    scale,
    useCORS: true,
    allowTaint: false,
    backgroundColor: "#ffffff",
    logging: false,
  });

  const imgData = canvas.toDataURL("image/png");
  const pageWidth = 210; // A4 mm
  const pageHeight = 297;
  const margin = 5;
  const imgAspect = canvas.height / canvas.width;
  const useLandscape = imgAspect > 1;
  const contentWidth = (useLandscape ? pageHeight : pageWidth) - 2 * margin;
  const contentHeight = (useLandscape ? pageWidth : pageHeight) - 2 * margin;
  let yOffset = margin;

  const pdf = new jsPDF({
    orientation: useLandscape ? "landscape" : "portrait",
    unit: "mm",
    format: "a4",
    compress: true,
  });

  const centerX = pdf.internal.pageSize.getWidth() / 2;

  if (options.chartName) {
    pdf.setFontSize(14);
    pdf.text(options.chartName, centerX, yOffset, { align: "center" });
    yOffset += 8;
  }
  if (options.birthDate || options.birthPlace) {
    pdf.setFontSize(10);
    if (options.birthDate) {
      pdf.text(`Birth: ${options.birthDate}`, centerX, yOffset, { align: "center" });
      yOffset += 5;
    }
    if (options.birthPlace) {
      pdf.text(options.birthPlace, centerX, yOffset, { align: "center" });
      yOffset += 8;
    }
  }

  const availableHeight = contentHeight - yOffset - 12;
  const imgHeight = (canvas.height * contentWidth) / canvas.width;
  const scaledHeight = Math.min(imgHeight, availableHeight);
  const scaledWidth = (canvas.width * scaledHeight) / canvas.height;

  pdf.addImage(
    imgData,
    "PNG",
    margin + (contentWidth - scaledWidth) / 2,
    yOffset,
    scaledWidth,
    scaledHeight
  );

  pdf.setFontSize(8);
  pdf.setTextColor(128, 128, 128);
  const footerY = pdf.internal.pageSize.getHeight() - 8;
  pdf.text("Generated by Jyotishya", centerX, footerY, { align: "center" });

  const fileName = options.fileName ?? `birth-chart-${Date.now()}.pdf`;
  pdf.save(fileName);
}

/**
 * Export multi-page report (e.g. KundliReport with PdfPage structure)
 * Wraps existing generatePdf logic with improved error handling
 */
export async function exportReportAsPdf(
  options: ReportExportOptions
): Promise<void> {
  if (!isBrowser()) {
    throw new Error("PDF export requires browser environment");
  }

  const element = document.getElementById(options.elementId);
  if (!element) {
    throw new Error(`Element with ID "${options.elementId}" not found`);
  }

  const pdf = new jsPDF("p", "mm", "a4");
  const pdfWidth = pdf.internal.pageSize.getWidth();
  const pdfHeight = pdf.internal.pageSize.getHeight();
  const pages = Array.from(element.children) as HTMLElement[];

  if (pages.length === 0) {
    throw new Error("No pages found in report root");
  }

  if (pages.length > PDF_LIMITS.MAX_PDF_PAGES) {
    throw new Error(
      `Report exceeds maximum page limit (${PDF_LIMITS.MAX_PDF_PAGES} pages)`
    );
  }

  const scale = getExportScale();

  for (let i = 0; i < pages.length; i++) {
    const page = pages[i];
    if (!(page instanceof HTMLElement)) continue;

    if (i > 0) pdf.addPage();

    const canvas = await html2canvas(page, {
      scale,
      useCORS: true,
      allowTaint: false,
      logging: false,
      backgroundColor: "#ffffff",
    });

    const imgData = canvas.toDataURL("image/png");
    pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight);
  }

  const fileName = options.fileName ?? "report.pdf";
  pdf.save(fileName);
}

/**
 * Export AI Jyotish reading as a native PDF using jsPDF text rendering.
 *
 * Unlike html2canvas-based exports, this renders markdown directly as
 * PDF-native text — always crisp at any zoom level.
 *
 * Supports: # h1, ## h2, ### h3, - bullets, **bold** (stripped), paragraphs
 */
export async function exportAIReportAsPdf({
  chartName,
  birthDetails,
  content,
  fileName,
  title,
}: {
  chartName: string;
  birthDetails?: { date: string; time: string; location: string };
  content: string;
  fileName: string;
  title: string;
}): Promise<void> {
  if (!isBrowser()) throw new Error("PDF export requires browser environment");

  const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const pageW = 210;
  const pageH = 297;
  const mLeft = 18;
  const mRight = 18;
  const mTop = 20;
  const mBottom = 18;
  const contentW = pageW - mLeft - mRight;
  let y = mTop;

  const newPage = () => {
    pdf.addPage();
    y = mTop;
  };

  const needsPageBreak = (h: number) => {
    if (y + h > pageH - mBottom) newPage();
  };

  // Strip inline bold/italic markers
  const clean = (s: string) =>
    s.replace(/\*\*(.*?)\*\*/g, "$1").replace(/\*(.*?)\*/g, "$1").replace(/__([^_]+)__/g, "$1");

  // ── Title block ────────────────────────────────────────────────────────────
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(22);
  pdf.setTextColor(20, 20, 80);
  const titleLines = pdf.splitTextToSize(title, contentW);
  titleLines.forEach((line: string) => {
    needsPageBreak(10);
    pdf.text(line, mLeft, y);
    y += 10;
  });

  y += 2;
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(12);
  pdf.setTextColor(80, 80, 120);
  pdf.text(`For: ${chartName}`, mLeft, y);
  y += 6;

  if (birthDetails) {
    pdf.setFontSize(10);
    pdf.setTextColor(100, 100, 100);
    pdf.text(
      `Date: ${birthDetails.date}  •  Time: ${birthDetails.time}  •  Place: ${birthDetails.location}`,
      mLeft,
      y,
    );
    y += 5;
  }

  // Divider
  y += 3;
  pdf.setDrawColor(220, 120, 40);
  pdf.setLineWidth(0.6);
  pdf.line(mLeft, y, pageW - mRight, y);
  y += 7;

  // ── Markdown content ───────────────────────────────────────────────────────
  const lines = content.split("\n");

  for (const rawLine of lines) {
    const line = rawLine.trimEnd();

    if (/^#{1}\s/.test(line)) {
      // H1
      const text = clean(line.replace(/^#\s+/, ""));
      needsPageBreak(10);
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(18);
      pdf.setTextColor(20, 40, 120);
      pdf.splitTextToSize(text, contentW).forEach((l: string) => {
        needsPageBreak(9);
        pdf.text(l, mLeft, y);
        y += 9;
      });
      y += 2;
    } else if (/^#{2}\s/.test(line)) {
      // H2
      const text = clean(line.replace(/^##\s+/, ""));
      needsPageBreak(9);
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(15);
      pdf.setTextColor(30, 60, 150);
      pdf.splitTextToSize(text, contentW).forEach((l: string) => {
        needsPageBreak(8);
        pdf.text(l, mLeft, y);
        y += 8;
      });
      y += 2;
    } else if (/^#{3}\s/.test(line)) {
      // H3
      const text = clean(line.replace(/^###\s+/, ""));
      needsPageBreak(7);
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(12);
      pdf.setTextColor(60, 80, 160);
      pdf.splitTextToSize(text, contentW).forEach((l: string) => {
        needsPageBreak(6.5);
        pdf.text(l, mLeft, y);
        y += 6.5;
      });
      y += 1;
    } else if (/^[-*]\s/.test(line)) {
      // Bullet
      const text = clean(line.replace(/^[-*]\s+/, ""));
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(11);
      pdf.setTextColor(40, 40, 40);
      const wrapped = pdf.splitTextToSize(text, contentW - 6);
      wrapped.forEach((l: string, i: number) => {
        needsPageBreak(5.5);
        pdf.text(i === 0 ? `•  ${l}` : `    ${l}`, mLeft + 2, y);
        y += 5.5;
      });
    } else if (line.trim() === "") {
      // Blank line → small paragraph gap
      y += 3;
    } else {
      // Normal paragraph text
      const text = clean(line.trim());
      if (!text) continue;
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(11);
      pdf.setTextColor(40, 40, 40);
      const wrapped = pdf.splitTextToSize(text, contentW);
      wrapped.forEach((l: string) => {
        needsPageBreak(5.5);
        pdf.text(l, mLeft, y);
        y += 5.5;
      });
      y += 2; // paragraph spacing
    }
  }

  // ── Page footers ───────────────────────────────────────────────────────────
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const totalPages = (pdf.internal as any).getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(8);
    pdf.setTextColor(160, 160, 160);
    pdf.text(
      `Generated by Jyotishya AI Astrologer  •  Page ${i} of ${totalPages}`,
      pageW / 2,
      pageH - 8,
      { align: "center" },
    );
  }

  pdf.save(fileName);
}
