import React from "react";

interface PdfPageProps {
  children: React.ReactNode;
  pageNumber?: number;
  title?: string;
}

/**
 * Represents a single A4 page in the PDF report.
 * Dimensions: 210mm x 297mm.
 * Includes Branding Header and Page Number Footer.
 */
export default function PdfPage({ children, pageNumber, title }: PdfPageProps) {
  return (
    <div
      className="relative flex flex-col bg-white"
      style={{
        width: "210mm",
        height: "297mm",
        padding: "15mm", // Standard printable margin
        pageBreakAfter: "always",
        overflow: "hidden", // Prevent spillover
      }}
    >
      {/* Header */}
      <div className="mb-8 flex items-center justify-between border-b-2 border-orange-500 pb-4">
        <div className="flex items-center gap-2">
          <span className="text-2xl">🕉️</span>
          <div>
            <h1 className="text-lg font-bold text-slate-900 leading-none">Jyotishya</h1>
            <p className="text-xs text-slate-500">Vedic Astrology Insights</p>
          </div>
        </div>
        {title && <h2 className="text-sm font-semibold uppercase tracking-wider text-orange-600">{title}</h2>}
      </div>

      {/* Content Area */}
      <div className="flex-1">
         {children}
      </div>

      {/* Footer */}
      <div className="mt-auto flex items-center justify-between border-t border-slate-200 pt-4 text-[10px] text-slate-400">
        <span>www.jyotishya.ai</span>
        <span>Generated by Jyotishya Engine</span>
        {pageNumber && <span>Page {pageNumber}</span>}
      </div>
    </div>
  );
}
