
import React from 'react';

export const ReportFooter: React.FC = () => {
  return (
    <div className="mt-auto pt-8 border-t border-slate-100 w-full text-center">
      <p className="text-slate-400 text-xs mb-1">
         Generated by Jyotishya Digital Astrology • {new Date().toLocaleDateString()}
      </p>
      <p className="text-slate-300 text-[10px]">
         Guidance for Life's Journey
      </p>
    </div>
  );
};
